# Sheet properties

In [15]:
%%javascript
IPython.OutputArea.prototype._should_scroll = function(lines) {
    return false;
}

<IPython.core.display.Javascript object>

# Imports

In [16]:
import sys
sys.path.append('/home/rcendre/classification')
from joblib import dump, load
from numpy import array, logspace
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from sklearn.svm import SVC
from sklearn.metrics import f1_score
from toolbox.classification.common import Data, Folds, IO, Tools
from toolbox.classification.parameters import Dermatology, Settings
from toolbox.transforms.common import FlattenTransform
from toolbox.transforms.labels import OrderedEncoder
from toolbox.views.common import Views, ViewsTools
from toolbox.models.models import DecisionVotingClassifier, ScoreVotingClassifier
from toolbox.transforms.images import HaralickImageTransform, SpatialImageTransform
import warnings
warnings.filterwarnings('ignore') 

# Parameters

In [17]:
# Advanced parameters
validation = 4
settings = Settings.get_default_dermatology()

# Patch classifier

In [18]:
patch = Dermatology.images(modality='Microscopy', data_type='Patch', use_unknown=False)
# Transform labels
label_encoder = OrderedEncoder().fit(['Normal', 'Benign', 'Malignant'])
Tools.transform(patch, {'datum': 'Label'}, label_encoder, 'LabelEncode')
# Transform groups
group_encoder = LabelEncoder().fit(array(patch['ID_Patient'].tolist()))
Tools.transform(patch, {'datum': 'ID_Patient'}, group_encoder, 'GroupEncode')
# Extract features 
Tools.transform(patch, {'datum': 'Datum'}, HaralickImageTransform(), 'Spatial')
# Make folds
Folds.build_group_folds(patch, {'datum': 'Datum', 'label_encode': 'LabelEncode', 'group': 'GroupEncode'}, validation)
IO.save(patch, f'Instances_PatchSpatial.pickle')

In [19]:
low_predictor = Pipeline([('scale', MinMaxScaler()),('clf', SVC(kernel='linear', class_weight='balanced', decision_function_shape='ovo', probability=True))])
low_params = {'clf__C': logspace(-2, 3, 6).tolist()}

## Evaluate

In [20]:
Tools.evaluate(patch, {'datum': 'Spatial', 'label_encode': 'LabelEncode'}, low_predictor, 'Evaluate', distribution=low_params)

In [21]:
from IPython.display import HTML
from IPython.display import display
display(HTML(ViewsTools.dataframe_renderer([Views.report(patch, {'label_encode': 'LabelEncode', 'eval': 'Evaluate'}, label_encoder)],
                                                                        title=[f'Test - Patch SVC'])))

## Fit

In [22]:
low_predictor = Tools.fit(patch, {'datum': 'Spatial', 'label_encode': 'LabelEncode'}, low_predictor, distribution=low_params)

In [23]:
dump(low_predictor, 'Instances_SpatialPredictor')

['Instances_SpatialPredictor']

# Sliding window

In [24]:
inputs_options = []
inputs_options.append((250,0))
inputs_options.append((250,25))
inputs_options.append((250,50))
inputs_options.append((500,0))
inputs_options.append((500,25))
inputs_options.append((500,50))

In [25]:
low_predictor = load('Instances_SpatialPredictor')
for size, overlap in inputs_options:
    inputs = Dermatology.sliding_images(size=size, overlap=overlap/100, modality='Microscopy')
    Tools.transform(inputs, {'datum': 'Datum'}, HaralickImageTransform(), 'Spatial')
    # Transform groups
    group_encoder = LabelEncoder().fit(array(inputs['ID_Patient'].tolist()))
    Tools.transform(inputs, {'datum': 'ID_Patient'}, group_encoder, 'GroupEncode')
    # Transform labels
    label_encoder = OrderedEncoder().fit(['Normal', 'Benign', 'Malignant'])
    Tools.transform(inputs, {'datum': 'Label'}, label_encoder, 'LabelEncode')
    # Make folds
    Folds.build_group_folds(inputs, {'datum': 'Datum', 'label_encode': 'LabelEncode', 'group': 'GroupEncode'}, validation)
    IO.save(inputs, f'Instances_Spatial_{size}_{overlap}.pickle')

# Low level predictions

In [26]:
for size, overlap in inputs_options:
    inputs = IO.load(f'Instances_Spatial_{size}_{overlap}.pickle')
    
    # Add scaling
    Tools.predict(inputs, {'datum': 'Spatial'}, low_predictor, Tools.PREDICTION, mask=inputs.Type != 'Full')
    Tools.predict_proba(inputs, {'datum': 'Spatial'}, low_predictor, Tools.PROBABILITY, mask=inputs.Type != 'Full')

    Data.build_bags(inputs, inputs.Type == 'Full', 'Reference', inputs.Type == 'Instance', 'Source', Tools.PREDICTION)
    Data.build_bags(inputs, inputs.Type == 'Full', 'Reference', inputs.Type == 'Instance', 'Source', Tools.PROBABILITY)

    # Filter elements
    inputs = inputs[inputs.Type == 'Full']
    
    # Low Level
    IO.save(inputs, f'Instances_LowSpatial_{size}_{overlap}.pickle')

# High level predictions

In [27]:
for size, overlap in inputs_options:
    inputs = IO.load(f'Instances_LowSpatial_{size}_{overlap}.pickle')
    
    # Decisions
    Tools.evaluate(inputs, {'datum': Tools.PREDICTION, 'label_encode': 'LabelEncode'}, DecisionVotingClassifier(mode='at_least_one', metric=f1_score), 'D_ALO')
    Tools.evaluate(inputs, {'datum': Tools.PREDICTION, 'label_encode': 'LabelEncode'}, DecisionVotingClassifier(mode='dynamic_thresh', metric=f1_score), 'D_DYN')

    # Score
    Tools.evaluate(inputs, {'datum': Tools.PROBABILITY, 'label_encode': 'LabelEncode'}, ScoreVotingClassifier(low='max', high='dynamic'), 'S_MAX')
    
    # SVC
    score_svc = Pipeline([('flat', FlattenTransform()), ('clf', SVC(probability=True))])
    score_params = {'clf__C': logspace(-2, 3, 6).tolist()}
    Tools.evaluate(inputs, {'datum': Tools.PROBABILITY, 'label_encode': 'LabelEncode'}, score_svc, 'High_SVC', distribution=score_params)

    # High Level    
    IO.save(inputs, f'Instances_HighSpatial_{size}_{overlap}.pickle')

[0.6875 0.375  0.125 ]
[0.75   0.1875 0.1875]
[0.6875 0.3125 0.1875]
[0.6875 0.3125 0.125 ]
[0.64 0.4  0.12]...!
[0.64 0.32 0.2 ]...
[0.64 0.32 0.16]...
[0.64 0.32 0.16]...
[0.55102041 0.34693878 0.12244898]
[0.69387755 0.34693878 0.18367347]
[0.55102041 0.34693878 0.20408163]
[0.55102041 0.36734694 0.14285714]
[0.5  0.5  0.25]...!
[0.5  0.5  0.25]...
[0.5  0.5  0.25]...
[0.5  0.75 0.25]...
[0.5  0.75 0.25]...!
[0.25 0.75 0.25]...
[0.25 0.75 0.  ]...
[0.5  0.75 0.25]...
[0.33333333 0.66666667 0.11111111]
[0.33333333 0.55555556 0.11111111]
[0.33333333 0.66666667 0.11111111]
[0.33333333 0.77777778 0.11111111]


## Analysis

In [28]:
from IPython.display import HTML
from IPython.display import display

label_encoder = OrderedEncoder().fit(['Normal', 'Benign', 'Malignant'])
models = ['D_ALO', 'D_DYN', 'S_MAX', 'High_SVC']

for size, overlap in inputs_options:
    inputs = IO.load(f'Instances_HighSpatial_{size}_{overlap}.pickle')
    
    for high_name in models:
        name = f'{high_name}_{size}_{overlap}'
        # Details and results
        display(HTML(ViewsTools.dataframe_renderer([Views.report(inputs, {'label_encode': 'LabelEncode', 'eval': high_name}, label_encoder)],
                                                                    title=[f'Test - {name}']))) 